Implement AssignE
AY2324S1-CS2103T-T08-3/tp pull request #106
Opened 2023-10-19 16:39 UTC by antonTan96

2023-10-19 22:20 UTC, aslam341 requested changes
We will need to create a `Project` model first. Currently the design is bad. `Project` is being represented as an attribute of the `Employee` model. What if you intend to add attributes to a project, such as `deadline` which we discussed. It would not be proper to add a `deadline` attribute under the `Employee` model, as that violates the [SoC principle](https://nus-cs2103-ay2324s1.github.io/website/book/principles/separationOfConcernsPrinciple/). The only way to achieve that requirement is to first create a `Project` model and then add a `deadline` attribute under it. The more features we add before implementing the `Project` model, the harder it will be to implement later on (will lead to extra time and effort required). With that being said, I am disinclined to approve this PR.

2023-10-20 00:27 UTC, antonTan96 commented
> We will need to create a `Project` model first. Currently the design is bad. `Project` is being represented as an attribute of the `Employee` model. What if you intend to add attributes to a project, such as `deadline` which we discussed. It would not be proper to add a `deadline` attribute under the `Employee` model, as that violates the [SoC principle](https://nus-cs2103-ay2324s1.github.io/website/book/principles/separationOfConcernsPrinciple/). The only way to achieve that requirement is to first create a `Project` model and then add a `deadline` attribute under it. The more features we add before implementing the `Project` model, the harder it will be to implement later on (will lead to extra time and effort required). With that being said, I am disinclined to approve this PR.

Currently `Employee` stores an empty `Project` that only has a name just for ease of UI purposes, and we can directly add `deadline` attribute to the `Project` class. Perhaps it was misleading that `Project` and `UniqueProjectList` are under the employee folder. I'll move them to a separate folder instead.

2023-10-22 17:06 UTC, aslam341 approved these changes

2023-10-23 12:04 UTC, aslam341 approved these changes
LGTM.

2023-10-23 12:05 UTC, merged