Developer Guide update for Storage component
AY2324S1-CS2103T-T08-3/tp pull request #234
Opened 2023-11-09 17:53 UTC by antonTan96

2023-11-09 19:05 UTC, aslam341 requested changes
There seems to be wrong command format usage in the diagrams.

2023-11-09 19:05 UTC, aslam341 commented on docs/diagrams/AddPSequenceDiagram.puml
> +[-> LogicManager : execute("addP pr/Project1 em/1")
Supposed to be `addP n/Project1 em/1`.

2023-11-09 19:05 UTC, aslam341 commented on docs/diagrams/AddPSequenceDiagram.puml
> +LogicManager -> TaskHubParser : parseCommand("addP pr/Project1 em/1")
Supposed to be `addP n/Project1 em/1`.

2023-11-10 06:39 UTC, rayyan35p requested changes
As mentioned by Aslam, the commands are using the wrong prefix. Also, maybe you can add multiple indexes in the command to show what the loop in the sequence diagram will be going through? Just a suggestion.

2023-11-10 06:39 UTC, rayyan35p commented on src/main/java/seedu/address/storage/JsonAdaptedProject.java
> +                checkEmployees(modeledTask.getEmployee(), employeeList);
Good job in extracting the method to apply SLAP! 👍

2023-11-10 13:45 UTC, rayyan35p approved these changes
LGTM!

2023-11-10 13:46 UTC, aslam341 approved these changes

2023-11-10 13:47 UTC, merged