Implement help command and user guide fixes.
AY2324S1-CS2103T-T08-3/tp pull request #92
Opened 2023-10-16 08:57 UTC by timleow

Add a quick guide to help command with 3 sections. It is a condensed version of the user guide.

**General Commands**, **Project Commands**, **Employee Commands**.

Also fix user guide, replacing persons with employees and `pr/` prefix to avoid conflict with `p/` for phone number.

2023-10-17 10:38 UTC, Chandan8186 requested changes
LGTM, but seems like there are conflicts to be resolved.

2023-10-18 04:05 UTC, Chandan8186 requested changes
There seem to be some differences in some of the command formats when compared with the implementation by @antonTan96, specifically how the `e/` prefix to assign employee to project is used (more details in [his PR](https://github.com/AY2324S1-CS2103T-T08-3/tp/pull/94)). Also, it seems that Anton has changed the `e/` prefix for adding email, to `em/` to avoid ambiguity.

2023-10-18 08:13 UTC, Chandan8186 approved these changes
LGTM!

2023-10-18 09:15 UTC, aslam341 approved these changes
LGTM. I understand that codecov fails due to added UI elements, so I am okay with the merge.

2023-10-18 09:17 UTC, aslam341 commented on docs/UserGuide.md
> +* employees matching at least one keyword will be returned (i.e. `OR` search).
Minor grammatical error, but `employees` should be changed to `Employees` in the next commit.

2023-10-18 09:28 UTC, merged